### ISSUE TITLE
Invalid combination of arguments to `draw_boolean(...)`

### ISSUE THREAD

**Issue by Zac-HD** [pschanely/hypothesis-crosshair#18]
[These assertions in Hypothesis](https://github.com/HypothesisWorks/hypothesis/blob/6e7921e19f9bbf87cd7cf3c4c2b0409aad0a2ee9/hypothesis-python/src/hypothesis/internal/conjecture/data.py#L2263-L2278) check that if `forced is True`, then `p > 0`, and vice-versa at the other end - because it would be invalid to generate the forced value otherwise.  However, the following example fails with Crosshair:

```python
from hypothesis import settings
from hypothesis.stateful import RuleBasedStateMachine, rule, run_state_machine_as_test

@run_state_machine_as_test
@settings(backend="crosshair", deadline=None)
class IntListRules(RuleBasedStateMachine):

    @rule()
    def a(self): pass

    @rule()
    def b(self): pass
```

I'm reporting it here because of the `draw_boolean()` symptom, but I actually find it pretty plausible that it's an issue in Crosshair's reasoning about the internal `FeatureStrategy` ([see here](https://github.com/HypothesisWorks/hypothesis/blob/6e7921e19f9bbf87cd7cf3c4c2b0409aad0a2ee9/hypothesis-python/src/hypothesis/strategies/_internal/featureflags.py)).  As usual, found in https://github.com/HypothesisWorks/hypothesis/pull/4034 🙂

**Comment by pschanely** [comment]
Hmm. Well, I'm not sure exactly HOW it fixes it, but if I make my provider respect the p=1 and p=0 cases, it seems to fix your example, so Ima roll with that. Fixed in 0.0.8!
